# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    tags:
      - "v*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lnx-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install SBCL
        run: sudo apt install sbcl -y

      - name: Install Quicklisp
        run: |
          curl -O https://beta.quicklisp.org/quicklisp.lisp
          sbcl --load quicklisp.lisp --eval "(quicklisp-quickstart:install)" --eval "(quit)"

      - name: Build cl-sucker
        run: |
          sbcl --load ~/quicklisp/setup.lisp --load ./cl-sucker.asd --eval "(ql:quickload 'cl-sucker)" --eval "(asdf:make :cl-sucker)"
          mv sucker lnx-sucker
          sbcl --dynamic-space-size 1024 --load ~/quicklisp/setup.lisp --load ./cl-sucker.asd --eval "(ql:quickload 'cl-sucker)" --eval "(asdf:make :cl-sucker)"
          mv sucker lnx-sucker-1024
          sbcl --dynamic-space-size 2048 --load ~/quicklisp/setup.lisp --load ./cl-sucker.asd --eval "(ql:quickload 'cl-sucker)" --eval "(asdf:make :cl-sucker)"
          mv sucker lnx-sucker-2048
          sbcl --dynamic-space-size 4096 --load ~/quicklisp/setup.lisp --load ./cl-sucker.asd --eval "(ql:quickload 'cl-sucker)" --eval "(asdf:make :cl-sucker)"
          mv sucker lnx-sucker-4096
          chmod +x lnx-*
          ls -lah .
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            lnx-sucker
            lnx-sucker-1024
            lnx-sucker-2048
            lnx-sucker-4096
  mac-build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install SBCL
        run: brew install sbcl

      - name: Install Quicklisp
        run: |
          curl -O https://beta.quicklisp.org/quicklisp.lisp
          sbcl --load quicklisp.lisp --eval "(quicklisp-quickstart:install)" --eval "(quit)"

      - name: Build cl-sucker
        run: |
          sbcl --load ~/quicklisp/setup.lisp --load ./cl-sucker.asd --eval "(ql:quickload 'cl-sucker)" --eval "(asdf:make :cl-sucker)"
          mv sucker mac-sucker
          sbcl --dynamic-space-size 1024 --load ~/quicklisp/setup.lisp --load ./cl-sucker.asd --eval "(ql:quickload 'cl-sucker)" --eval "(asdf:make :cl-sucker)"
          mv sucker mac-sucker-1024
          sbcl --dynamic-space-size 2048 --load ~/quicklisp/setup.lisp --load ./cl-sucker.asd --eval "(ql:quickload 'cl-sucker)" --eval "(asdf:make :cl-sucker)"
          mv sucker mac-sucker-2048
          sbcl --dynamic-space-size 4096 --load ~/quicklisp/setup.lisp --load ./cl-sucker.asd --eval "(ql:quickload 'cl-sucker)" --eval "(asdf:make :cl-sucker)"
          mv sucker mac-sucker-4096
          chmod +x mac-*
          ls -lah .
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            mac-sucker
            mac-sucker-1024
            mac-sucker-2048
            mac-sucker-4096
  win-build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install SBCL
        run: choco install sbcl

      - name: Build SBCL
        run: |
            curl -LO https://downloads.sourceforge.net/project/sbcl/sbcl/2.2.0/sbcl-2.2.0-source.tar.bz2
            7z x sbcl-2.2.0-source.tar.bz2
            dir
            7z x sbcl-2.2.0-source.tar
            dir
            cd sbcl-2.2.0
            sh make.sh --with-fancy --with-sb-core-compression
            sh install.sh

      - name: Install Quicklisp
        run: |
          $env:Path = "C:\Program Files\sbcl\bin;" + $env:Path
          $env:SBCL_HOME = "C:\Program Files\sbcl\lib\sbcl"
          curl -O https://beta.quicklisp.org/quicklisp.lisp
          sbcl --load quicklisp.lisp --eval "(quicklisp-quickstart:install)" --eval "(quit)"
          echo '(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname)))) (when (probe-file quicklisp-init) (load quicklisp-init)))' > ~/.sbclrc

      - name: Build cl-sucker
        run: |
          $env:Path = "C:\Program Files\sbcl\bin;" + $env:Path
          $env:SBCL_HOME = "C:\Program Files\sbcl\lib\sbcl"
          sbcl --load ./cl-sucker.asd --eval "(ql:quickload 'cl-sucker)" --eval "(asdf:make :cl-sucker)"
          mv sucker.exe win-sucker.exe
          sbcl --dynamic-space-size 1024 --load ./cl-sucker.asd --eval "(ql:quickload 'cl-sucker)" --eval "(asdf:make :cl-sucker)"
          mv sucker.exe win-sucker-1024.exe
          sbcl --dynamic-space-size 2048 --load ./cl-sucker.asd --eval "(ql:quickload 'cl-sucker)" --eval "(asdf:make :cl-sucker)"
          mv sucker.exe win-sucker-2048.exe
          sbcl --dynamic-space-size 4096 --load ./cl-sucker.asd --eval "(ql:quickload 'cl-sucker)" --eval "(asdf:make :cl-sucker)"
          mv sucker.exe win-sucker-4096.exe
          dir

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            win-sucker.exe
            win-sucker-1024.exe
            win-sucker-2048.exe
            win-sucker-4096.exe
